# Generated by Django 4.1.3 on 2022-12-05 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appFamiliares', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='familiar',
            name='presencia',
        ),
        migrations.AddField(
            model_name='familiar',
            name='edad',
            field=models.IntegerField(default=20),
            preserve_default=False,
        ),
    ]
